/**
 * filter.pipe.ts — Day 2 Part A: Pure Pipe Behavior Demo
 *
 * PURPOSE: Demonstrates a pure pipe that filters an array — AND the gotcha
 * that trips up every beginner: pure pipes do NOT re-run when you mutate
 * an array in place.
 *
 * ──────────────────────────────────────────────────────────────────
 * ⚠️ PURE PIPE RE-EVALUATION BEHAVIOR — READ THIS CAREFULLY
 * ──────────────────────────────────────────────────────────────────
 *
 * Angular pipes are PURE by default. A pure pipe only re-runs its
 * transform() method when the INPUT REFERENCE changes — not when
 * the contents of an array or object change.
 *
 * EXAMPLE OF THE GOTCHA:
 *
 *   // This WON'T trigger the pipe to re-run:
 *   this.movies.push(newMovie);          // same array reference!
 *
 *   // This WILL trigger the pipe to re-run:
 *   this.movies = [...this.movies, newMovie]; // new array reference!
 *
 * WHY? Because push() modifies the existing array in place. The array
 * reference hasn't changed, so Angular's change detection sees the same
 * object and skips the pipe. Spread (...) creates a brand-new array,
 * which IS a new reference, so Angular re-runs the pipe.
 *
 * SOLUTION OPTIONS:
 * 1. Always create a new array (recommended — works with pure pipes)
 * 2. Mark the pipe as pure: false (impure) — re-runs on EVERY change
 *    detection cycle, which is expensive and usually unnecessary
 *
 * In this course we always use option 1: immutable array updates.
 * ──────────────────────────────────────────────────────────────────
 *
 * USAGE IN TEMPLATE:
 *   {{ movies | filter:'genre':'Action' }}
 *
 * Generated by: ng generate pipe filter --standalone
 */
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'filter',
  standalone: true,
  pure: true // Explicitly pure — will NOT re-run on in-place array mutation
})
export class FilterPipe implements PipeTransform {

  /**
   * Filters an array of objects by matching a property value.
   *
   * @param items — the array to filter
   * @param property — the property name to check on each item
   * @param value — the value to match against
   * @returns a new filtered array (or the original if no filter is applied)
   */
  transform(items: any[], property: string, value: string): any[] {
    // Guard: if no items or no filter value, return everything
    if (!items || !property || !value) {
      return items;
    }

    // Filter and return a NEW array — pure pipe safe
    return items.filter(item => item[property] === value);
  }
}
