/**
 * truncate.pipe.ts — Day 2 Part A: Custom Pure Pipe
 *
 * PURPOSE: Demonstrates how to build a custom pure pipe with a
 * configurable parameter. Truncates a string to a maximum character
 * limit and appends "..." if the string was longer.
 *
 * USAGE IN TEMPLATE:
 *   {{ longText | truncate }}          → defaults to 50 characters
 *   {{ longText | truncate:100 }}      → custom limit of 100 characters
 *
 * PURE PIPE BEHAVIOR:
 * This pipe is pure (the default). Angular only re-runs transform()
 * when the INPUT VALUE or PARAMETERS change by reference. If you mutate
 * a string in place (which you can't — strings are immutable), the pipe
 * would not re-run. This matters more for arrays/objects (see filter.pipe.ts).
 *
 * Generated by: ng generate pipe truncate --standalone
 */
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'truncate', // Use as {{ value | truncate }} or {{ value | truncate:limit }}
  standalone: true, // Standalone — import directly into component imports array
  pure: true // Default; stated explicitly for teaching clarity
})
export class TruncatePipe implements PipeTransform {

  /**
   * Truncates a string to the given character limit.
   *
   * @param value — the input string to truncate
   * @param limit — maximum number of characters (default: 50)
   * @returns the truncated string with "..." appended if it was shortened
   */
  transform(value: string, limit: number = 50): string {
    // Guard: if the string is shorter than the limit, return it unchanged
    if (!value || value.length <= limit) {
      return value;
    }

    // Slice to the limit and append ellipsis
    return value.slice(0, limit) + '...';
  }
}
