/**
 * task-list.component.ts — Day 2 Part A: Control Flow & Template Concepts
 *
 * PURPOSE: Demonstrates the modern Angular control flow syntax and
 * template features in a single realistic component:
 *   - @for with required track — iterates a task list
 *   - @if / @else using ng-template for the else block
 *   - ng-container — applies @if without adding a real DOM element
 *   - ng-template — used as the @else block AND as a reusable snippet
 *   - @let local variable — defines a filtered count once, used in
 *     both @if and interpolation
 *   - [ngClass] — conditionally applies CSS classes based on task status
 *
 * Generated by: ng generate component task-list --standalone
 */
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; // Provides [ngClass]

/** Task interface — defines the shape of a task item */
interface Task {
  id: number;
  title: string;
  status: 'todo' | 'in-progress' | 'done';
}

@Component({
  selector: 'app-task-list',
  standalone: true,
  imports: [CommonModule], // CommonModule provides [ngClass]
  templateUrl: './task-list.component.html',
  styleUrl: './task-list.component.css'
})
export class TaskListComponent {

  /** Hard-coded task list for demonstration purposes */
  tasks: Task[] = [
    { id: 1, title: 'Set up project', status: 'done' },
    { id: 2, title: 'Build header component', status: 'in-progress' },
    { id: 3, title: 'Add routing', status: 'todo' },
    { id: 4, title: 'Write unit tests', status: 'todo' },
    { id: 5, title: 'Deploy to production', status: 'todo' }
  ];

  /**
   * Removes a task by id — creates a NEW array so pure pipes would detect the change.
   * Mutating in place (splice) would NOT trigger a pure pipe update.
   */
  removeTask(taskId: number): void {
    this.tasks = this.tasks.filter(t => t.id !== taskId);
  }
}
