/**
 * app.config.ts — Application-level configuration.
 *
 * WHAT THIS FILE DEMONSTRATES:
 * - ApplicationConfig type — the shape Angular expects for app-level config
 * - The providers array — currently empty because this app has no services,
 *   no routing, and no HTTP. On Day 3 you'll add provideRouter(routes) here.
 *   On Day 4 you'll add provideHttpClient() here.
 *
 * CLI equivalent: Auto-generated by `ng new personal-bio-card`.
 */

import { ApplicationConfig } from '@angular/core';

// The app config object passed as the second argument to bootstrapApplication()
export const appConfig: ApplicationConfig = {
  // providers is where you register app-wide services and features
  // Empty now — this app is purely component-based with no DI needs yet
  providers: []
};
