/**
 * card.component.ts — Day 2 Part A: Single-Slot Content Projection
 *
 * PURPOSE: Demonstrates ng-content with a single default slot.
 * The CardComponent acts as a reusable wrapper — whatever the parent
 * places between <app-card> and </app-card> is projected into the
 * single <ng-content> slot inside this component's template.
 *
 * Think of it like a picture frame: this component IS the frame,
 * and the parent decides what picture goes inside.
 *
 * Generated by: ng generate component card --standalone
 */
import { Component } from '@angular/core';

@Component({
  selector: 'app-card', // Use <app-card>...</app-card> in parent templates
  standalone: true, // Standalone component — no NgModule needed
  templateUrl: './card.component.html', // External template file
  styleUrl: './card.component.css' // External stylesheet
})
export class CardComponent {
  // No logic needed — this component is a pure wrapper.
  // All content comes from the parent via ng-content projection.
}
