/**
 * app.component.ts — The root component of the Personal Bio Card app.
 *
 * WHAT THIS FILE DEMONSTRATES:
 * - standalone: true — this component manages its own dependencies
 * - imports array — every child component used in the template must be listed here
 * - templateUrl and styleUrl — always separate files, never inline
 * - Passing data to child components via property binding and @Input()
 * - If you remove a component from imports but keep it in the template,
 *   you'll get the "not a known element" error
 *
 * CLI equivalent: Auto-generated by `ng new personal-bio-card`.
 */

import { Component } from '@angular/core';

// Import every child component this template uses
// If you forget one of these imports, Angular throws: "'app-xyz' is not a known element"
import { HeaderComponent } from './header/header.component';
import { BioCardComponent } from './bio-card/bio-card.component';
import { SkillBadgeComponent } from './skill-badge/skill-badge.component';
import { FooterComponent } from './footer/footer.component';

@Component({
  // selector — the HTML tag used to render this component: <app-root>
  selector: 'app-root',

  // standalone: true — this component does not need an NgModule
  standalone: true,

  // imports — register every component, directive, or pipe this template uses
  // Try removing one and watch the "not a known element" error appear!
  imports: [
    HeaderComponent,
    BioCardComponent,
    SkillBadgeComponent,
    FooterComponent
  ],

  // Always use separate template and style files — never inline
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  /**
   * These properties hold the bio data displayed on the card.
   * In a real app this might come from an API — but on Day 1 we use
   * hard-coded values to focus on component structure, not data fetching.
   */

  // Data passed to HeaderComponent via [title] property binding
  pageTitle = 'Personal Bio Card';

  // Data passed to BioCardComponent via [name], [role], [bio], [avatarUrl]
  userName = 'Alex Morgan';
  userRole = 'Frontend Developer';
  userBio = 'Passionate about building accessible, performant web applications with Angular. Loves hiking, coffee, and clean component architecture.';
  userAvatarUrl = 'https://i.pravatar.cc/150?img=32';

  // Array of skills — each one becomes a SkillBadgeComponent via property binding
  skills: string[] = [
    'Angular',
    'TypeScript',
    'HTML & CSS',
    'RxJS',
    'Node.js'
  ];
}
