/**
 * app.component.ts — Day 2 Part A: Root Component
 *
 * PURPOSE: Demonstrates how to USE the components and pipes created
 * in this lesson. The AppComponent acts as the parent, projecting
 * content into CardComponent and LayoutCardComponent, and rendering
 * TaskListComponent and MovieListComponent.
 *
 * Generated by: ng generate component app --standalone (auto-generated at project creation)
 */
import { Component } from '@angular/core';
import { CardComponent } from './card/card.component';
import { LayoutCardComponent } from './layout-card/layout-card.component';
import { TaskListComponent } from './task-list/task-list.component';
import { MovieListComponent } from './movie-list/movie-list.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CardComponent,       // Single-slot ng-content demo
    LayoutCardComponent, // Named-slot ng-content demo
    TaskListComponent,   // Control flow demo (@for, @if, @let, [ngClass])
    MovieListComponent   // @switch, [ngStyle], pipes demo
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  /** Application title — displayed in the header */
  title = 'Day 2A — Content Projection, Directives & Pipes';
}
