/**
 * movie-list.component.ts — Day 2 Part A: @switch, [ngStyle], Pipes
 *
 * PURPOSE: Demonstrates several template concepts in one realistic component:
 *   - @switch / @case — renders different badge markup per genre
 *   - [ngStyle] — inline style binding for dynamic rating bar width
 *   - Built-in pipes: date, currency, uppercase, async
 *   - Custom FilterPipe — filtering movies by genre
 *   - Custom TruncatePipe — truncating long descriptions
 *
 * Generated by: ng generate component movie-list --standalone
 */
import { Component } from '@angular/core';
import { CommonModule, AsyncPipe, DatePipe, CurrencyPipe, UpperCasePipe } from '@angular/common';
import { FilterPipe } from '../pipes/filter.pipe';
import { TruncatePipe } from '../pipes/truncate.pipe';
import { BehaviorSubject } from 'rxjs';

/** Movie interface — defines the shape of a movie item */
interface Movie {
  id: number;
  title: string;
  genre: 'Action' | 'Comedy' | 'Drama' | 'Sci-Fi';
  description: string;
  releaseDate: string; // ISO date string
  ticketPrice: number;
  rating: number; // 0–10
}

@Component({
  selector: 'app-movie-list',
  standalone: true,
  imports: [
    CommonModule,    // Provides [ngStyle]
    DatePipe,        // Built-in: formats dates
    CurrencyPipe,    // Built-in: formats currency
    UpperCasePipe,   // Built-in: transforms text to uppercase
    AsyncPipe,       // Built-in: subscribes to Observable in template
    FilterPipe,      // Custom: filters array by property value
    TruncatePipe     // Custom: truncates long strings
  ],
  templateUrl: './movie-list.component.html',
  styleUrl: './movie-list.component.css'
})
export class MovieListComponent {

  /** The currently selected genre filter — empty string means "show all" */
  selectedGenre = '';

  /** BehaviorSubject to demonstrate the async pipe — holds the page title */
  pageTitle$ = new BehaviorSubject<string>('Now Showing');

  /** Hard-coded movie list for demonstration */
  movies: Movie[] = [
    {
      id: 1,
      title: 'Galactic Frontier',
      genre: 'Sci-Fi',
      description: 'A team of astronauts discovers a wormhole leading to an uncharted galaxy filled with ancient alien civilizations and mysterious energy sources.',
      releaseDate: '2025-06-15',
      ticketPrice: 14.99,
      rating: 8.5
    },
    {
      id: 2,
      title: 'Laugh Track',
      genre: 'Comedy',
      description: 'Two rival stand-up comedians are forced to share the stage at a comedy festival, leading to unexpected friendship and hilarious mishaps.',
      releaseDate: '2025-03-22',
      ticketPrice: 11.50,
      rating: 7.2
    },
    {
      id: 3,
      title: 'Steel Thunder',
      genre: 'Action',
      description: 'An ex-military pilot must stop a rogue AI from taking control of the global defense network in a race against time.',
      releaseDate: '2025-08-01',
      ticketPrice: 15.99,
      rating: 9.0
    },
    {
      id: 4,
      title: 'Quiet Harbor',
      genre: 'Drama',
      description: 'A retired fisherman reconnects with his estranged daughter when she returns to their small coastal town after twenty years.',
      releaseDate: '2025-01-10',
      ticketPrice: 10.00,
      rating: 8.8
    },
    {
      id: 5,
      title: 'Neon Chase',
      genre: 'Action',
      description: 'In a neon-lit cyberpunk city, a street racer uncovers a conspiracy that threatens the entire underground racing circuit.',
      releaseDate: '2025-11-05',
      ticketPrice: 13.50,
      rating: 7.8
    }
  ];

  /** Available genres for the filter buttons */
  genres: string[] = ['Action', 'Comedy', 'Drama', 'Sci-Fi'];

  /**
   * Sets the active genre filter.
   * Passing an empty string clears the filter and shows all movies.
   */
  filterByGenre(genre: string): void {
    this.selectedGenre = genre;
  }
}
