/**
 * main.ts — The entry point for the Angular application.
 *
 * WHAT THIS FILE DEMONSTRATES:
 * - bootstrapApplication() starts the app with a root component (AppComponent)
 * - The second argument is the app-level configuration from app.config.ts
 * - This replaces the legacy bootstrapModule(AppModule) pattern
 *
 * CLI equivalent: This file is auto-generated by `ng new personal-bio-card`.
 */

// bootstrapApplication is the modern way to start an Angular app (Angular 17+)
import { bootstrapApplication } from '@angular/platform-browser';

// AppComponent is the root component — the first thing Angular renders
import { AppComponent } from './app/app.component';

// appConfig holds providers (empty for now — filled with router/HTTP on Days 3–4)
import { appConfig } from './app/app.config';

// Start the application: render AppComponent using the providers in appConfig
bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err)); // Log any startup errors to the console
