/**
 * layout-card.component.ts — Day 2 Part A: Named Content Projection Slots
 *
 * PURPOSE: Demonstrates ng-content with NAMED slots using the select attribute.
 * The parent decides what goes in the header, body, and footer areas.
 * Also demonstrates ngAfterContentInit lifecycle hook — it fires once
 * after Angular projects the parent's content into the slots.
 *
 * IMPORTANT: We do NOT use @ContentChild here. That decorator is covered
 * in Extended Topics and has not been taught yet. The sole purpose of
 * ngAfterContentInit in this example is to show WHEN the hook fires.
 *
 * Generated by: ng generate component layout-card --standalone
 */
import { Component, AfterContentInit } from '@angular/core';

@Component({
  selector: 'app-layout-card', // Use <app-layout-card> in parent templates
  standalone: true, // Standalone — no NgModule
  templateUrl: './layout-card.component.html',
  styleUrl: './layout-card.component.css'
})
export class LayoutCardComponent implements AfterContentInit {

  /**
   * ngAfterContentInit — fires ONCE after Angular projects external content
   * into this component's <ng-content> slots.
   *
   * This is the right place to react to projected content being ready.
   * We simply log a message here to prove the hook fires.
   * DO NOT use @ContentChild — it has not been taught yet.
   */
  ngAfterContentInit(): void {
    // This runs once after the parent's projected content is rendered
    console.log('[LayoutCardComponent] Projected content is ready!');
  }
}
